### ISSUE TITLE
Remove old containers after stopping it

### ISSUE THREAD

**Issue by KnightNiwrem** [source-academy/tools#7]
Pardon the lack of a PR - outside now.

Suggest changing command of `make stop` to:
`docker stop $(docker ps | grep cadet | awk '{print $1;}') && docker rm $(docker container ls -a | grep cadet | awk '{print $1;}')`

Each stopped container take up about 800mb of space, so this is significant.

**Comment by ning-y** [comment]
Can also look into `docker rm $(docker stop $(docker ps -a -q --filter ancestor=cadet --format="{{.ID}}"))`. Reference: https://stackoverflow.com/a/32074098/. We've come across at least two cases of `make stop` failing to stop the docker containers successfully, removing all the piping may help.

**Comment by KnightNiwrem** [comment]
Assuming fixed.
